# CMake generated Testfile for 
# Source directory: D:/AegisRTC
# Build directory: D:/AegisRTC/build-msvc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[format_selector_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_format_selector_test.exe")
  set_tests_properties([=[format_selector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;115;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[format_selector_test]=] "D:/AegisRTC/build-msvc/Release/aegis_format_selector_test.exe")
  set_tests_properties([=[format_selector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;115;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[format_selector_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_format_selector_test.exe")
  set_tests_properties([=[format_selector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;115;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[format_selector_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_format_selector_test.exe")
  set_tests_properties([=[format_selector_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;115;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[format_selector_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[network_simulator_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_network_simulator_test.exe")
  set_tests_properties([=[network_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;138;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[network_simulator_test]=] "D:/AegisRTC/build-msvc/Release/aegis_network_simulator_test.exe")
  set_tests_properties([=[network_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;138;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[network_simulator_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_network_simulator_test.exe")
  set_tests_properties([=[network_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;138;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[network_simulator_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_network_simulator_test.exe")
  set_tests_properties([=[network_simulator_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;138;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[network_simulator_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[wire_protocol_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_wire_protocol_test.exe")
  set_tests_properties([=[wire_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;158;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[wire_protocol_test]=] "D:/AegisRTC/build-msvc/Release/aegis_wire_protocol_test.exe")
  set_tests_properties([=[wire_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;158;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[wire_protocol_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_wire_protocol_test.exe")
  set_tests_properties([=[wire_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;158;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[wire_protocol_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_wire_protocol_test.exe")
  set_tests_properties([=[wire_protocol_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;158;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[wire_protocol_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[frame_reassembler_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_frame_reassembler_test.exe")
  set_tests_properties([=[frame_reassembler_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;180;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[frame_reassembler_test]=] "D:/AegisRTC/build-msvc/Release/aegis_frame_reassembler_test.exe")
  set_tests_properties([=[frame_reassembler_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;180;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[frame_reassembler_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_frame_reassembler_test.exe")
  set_tests_properties([=[frame_reassembler_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;180;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[frame_reassembler_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_frame_reassembler_test.exe")
  set_tests_properties([=[frame_reassembler_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;180;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[frame_reassembler_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[nack_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_nack_test.exe")
  set_tests_properties([=[nack_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;202;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[nack_test]=] "D:/AegisRTC/build-msvc/Release/aegis_nack_test.exe")
  set_tests_properties([=[nack_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;202;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[nack_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_nack_test.exe")
  set_tests_properties([=[nack_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;202;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[nack_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_nack_test.exe")
  set_tests_properties([=[nack_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;202;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[nack_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[retransmission_cache]=] "D:/AegisRTC/build-msvc/Debug/aegis_retransmission_cache_test.exe")
  set_tests_properties([=[retransmission_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;222;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[retransmission_cache]=] "D:/AegisRTC/build-msvc/Release/aegis_retransmission_cache_test.exe")
  set_tests_properties([=[retransmission_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;222;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[retransmission_cache]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_retransmission_cache_test.exe")
  set_tests_properties([=[retransmission_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;222;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[retransmission_cache]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_retransmission_cache_test.exe")
  set_tests_properties([=[retransmission_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;222;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[retransmission_cache]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[retransmission_e2e_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_retransmission_e2e_test.exe")
  set_tests_properties([=[retransmission_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;246;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[retransmission_e2e_test]=] "D:/AegisRTC/build-msvc/Release/aegis_retransmission_e2e_test.exe")
  set_tests_properties([=[retransmission_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;246;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[retransmission_e2e_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_retransmission_e2e_test.exe")
  set_tests_properties([=[retransmission_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;246;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[retransmission_e2e_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_retransmission_e2e_test.exe")
  set_tests_properties([=[retransmission_e2e_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;246;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[retransmission_e2e_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[network_monitor_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_network_monitor_test.exe")
  set_tests_properties([=[network_monitor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;267;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[network_monitor_test]=] "D:/AegisRTC/build-msvc/Release/aegis_network_monitor_test.exe")
  set_tests_properties([=[network_monitor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;267;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[network_monitor_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_network_monitor_test.exe")
  set_tests_properties([=[network_monitor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;267;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[network_monitor_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_network_monitor_test.exe")
  set_tests_properties([=[network_monitor_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;267;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[network_monitor_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[adaptive_controller_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_adaptive_controller_test.exe")
  set_tests_properties([=[adaptive_controller_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;287;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[adaptive_controller_test]=] "D:/AegisRTC/build-msvc/Release/aegis_adaptive_controller_test.exe")
  set_tests_properties([=[adaptive_controller_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;287;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[adaptive_controller_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_adaptive_controller_test.exe")
  set_tests_properties([=[adaptive_controller_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;287;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[adaptive_controller_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_adaptive_controller_test.exe")
  set_tests_properties([=[adaptive_controller_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;287;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[adaptive_controller_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ffmpeg_video_encoder_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_ffmpeg_video_encoder_test.exe")
  set_tests_properties([=[ffmpeg_video_encoder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;327;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ffmpeg_video_encoder_test]=] "D:/AegisRTC/build-msvc/Release/aegis_ffmpeg_video_encoder_test.exe")
  set_tests_properties([=[ffmpeg_video_encoder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;327;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ffmpeg_video_encoder_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_ffmpeg_video_encoder_test.exe")
  set_tests_properties([=[ffmpeg_video_encoder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;327;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ffmpeg_video_encoder_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_ffmpeg_video_encoder_test.exe")
  set_tests_properties([=[ffmpeg_video_encoder_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;327;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[ffmpeg_video_encoder_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[video_encoder_factory_test]=] "D:/AegisRTC/build-msvc/Debug/aegis_video_encoder_factory_test.exe")
  set_tests_properties([=[video_encoder_factory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;367;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[video_encoder_factory_test]=] "D:/AegisRTC/build-msvc/Release/aegis_video_encoder_factory_test.exe")
  set_tests_properties([=[video_encoder_factory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;367;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[video_encoder_factory_test]=] "D:/AegisRTC/build-msvc/MinSizeRel/aegis_video_encoder_factory_test.exe")
  set_tests_properties([=[video_encoder_factory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;367;add_test;D:/AegisRTC/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[video_encoder_factory_test]=] "D:/AegisRTC/build-msvc/RelWithDebInfo/aegis_video_encoder_factory_test.exe")
  set_tests_properties([=[video_encoder_factory_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/AegisRTC/CMakeLists.txt;367;add_test;D:/AegisRTC/CMakeLists.txt;0;")
else()
  add_test([=[video_encoder_factory_test]=] NOT_AVAILABLE)
endif()
